[package]
name = "kernel-core"
version = "0.1.0"
edition = "2024"
description = "Core kernel library of Subatomic OS."

[dependencies]
spin = { version = "0.12.3" }
portable-atomic = { version = "1.15.0", default-features = false, features = ["require-cas"] }
bitflags = { version = "2.13.2", default-features = false }

embedded-graphics = { version = "0.8.2", features = [ "fixed_point" ] }
ratatui = { version = "0.30.2", default-features = false }
mousefood = { git = "https://github.com/j-g00da/mousefood", rev = "693d82a" }
ustyle = "0.1.1"

heapless = "0.9.3"
crossbeam-queue = { version = "0.3.14", default-features = false, features = [ "alloc" ] }
hashbrown = { version = "0.17.1", default-features = false, features = ["inline-more"] }
rapidhash = { version = "4.5.1", default-features = false, features = ["nightly", "unsafe"] }
time = { version = "0.3.55", default-features = false, features = ["alloc"] }
no-pico-args = "0.5.1"
anyhow = { version = "1.0.104", default-features = false }

pci_types = { version = "0.10.1", optional = true }
virtio-drivers = { version = "0.13.0", optional = true }
object = { version = "0.40.0", default-features = false, features = ["read"] }
pc-keyboard = { workspace = true }
limine = { workspace = true }
log = { workspace = true }

[features]
default = []
qemu-exit = []
pci = ["pci_types", "virtio-drivers"]

[lib]
name = "kernel_core"
path = "src/lib.rs"
test = false
bench = false
