cargo-features = ["profile-rustflags"]

[workspace]
members = ["kernel-core", "kernel-x86_64"]
resolver = "3"

[workspace.dependencies]
limine = "0.6.5"
log = { version = "0.4.34", features = ["release_max_level_info"] }
pc-keyboard = "0.9.0"

[package]
name = "kernel"
version = "0.1.0"
edition = "2024"
description = "Main kernel binary of Subatomic OS"

[dependencies]
kernel-core = { path = "kernel-core" }
log = { workspace = true }

[features]
default = []
qemu-exit = ["kernel-core/qemu-exit"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
kernel-x86_64 = { path = "kernel-x86_64" }

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false
